### PR TITLE
Swedish Translation (sv)

### PR DESCRIPTION
**Pull request by drygnet**
Swedish translation

### CODE REVIEW

**Review by Vimux — APPROVED** [review]
Thank you!

**Comment by drygnet** [comment]
You are welcome, but credit where credit is due.

I'm a native Swedish speaker, and I've double checked the translation and it is more than fine, if not perfect.

But ChatGPT with GPT-4 did all of it.

Translate this file to Swedish, ask questions if anything is unclear. Answer in a code block that i can copy
<PASTE> [enter]

**Comment by Vimux** [comment]
To complete the picture, you should have asked ChatGPT to write a confessional reply to my thank you.

**Comment by drygnet** [comment]
Well, with Copilot X I don’t even need to ask 

Anyway glad to help, love the theme. Out

**Pull request merged**
