### PR TITLE
Add blogroll

### PR DESCRIPTION
**Pull request by cdyson37**
Also from http://dukeellington.org.uk. This adds a blogroll/list of links as a side panel widget.

### CODE REVIEW

**Comment by cdyson37** [comment]
The side menu looks nice, but I couldn't figure out how to make it consist of external links rather than internal pages. Is there some way to do this? (Apologies I am a Hugo noob.)

**Comment by cdyson37** [comment]
Aside: a bit confused it fails the tests. `blogroll.html` ends with exactly one newline, which I would have thought pretty standard, but it complains `unexpected final newline`. Surely it's fairly standard for every line to end with a `\n`?

**Comment by Vimux** [comment]
> The side menu looks nice, but I couldn't figure out how to make it consist of external links rather than internal pages. Is there some way to do this? (Apologies I am a Hugo noob.)

External links should work just as well.

```
[menu]
  [[menu.side]]
    name = "About"
    url = "/about/"

  [[menu.side]]
    name = "Github"
    url = "https://github.com/"
```


> Aside: a bit confused it fails the tests. `blogroll.html` ends with exactly one newline, which I would have thought pretty standard, but it complains `unexpected final newline`. Surely it's fairly standard for every line to end with a `\n`?

In most cases, I add final newline, but...

Every empty line in dependent `*.html` partial generate empty line in the main template. This is not suitable for me for some reasons. As a result, no final newlines in the `*.html` files in my Hugo themes.

**Comment by cdyson37** [comment]
Many thanks for explaining both points. Looks like the above covers my needs.

**Comment by cdyson37** [comment]
I've come back to this and I remembered my original problem: the title of the menu is fixed - I'd like to change it to e.g. "Links". Could this be made a theme/widget parameter? I'm happy to submit another PR.

**Comment by Vimux** [comment]
> I've come back to this and I remembered my original problem: the title of the menu is fixed...

Not true. It's is `i18n` powered and you can change translation strings (`sidemenu_title`, for example) through additional file in i18n/ at the root of your project.

[Translation of Strings](https://gohugo.io/content-management/multilingual/#translation-of-strings):

> Translations are collected from the themes/<THEME>/i18n/ folder (built into the theme), as well as translations present in i18n/ at the root of your project. In the i18n, the translations will be merged and take precedence over what is in the theme folder.

**Comment by cdyson37** [comment]
Ah, did not realise you could specialise translations like that. Thank you!

**Pull request closed without merging**
