### PR TITLE
add Mastodon social widget support

### PR DESCRIPTION
**Pull request by shakasan**
Small PR to add Mastodon support to the social widget + doc update accordingly

### CODE REVIEW

**Comment by Vimux** [comment]
Greetings. Any problems with using custom social links for this?

**Comment by shakasan** [comment]
No issue with custom social links, but a bit easier for end-user to setup it and with the right icon directly available.
Just a proposition of contribution ;-)

**Comment by thomaslevesque** [comment]
Nice! May I suggest you also add a link to the page `<head>`? This will allow Mastodon to verify that you own the link, and add a checkmark on the link on your profile page:
image
```html
<link rel="me" href="https://mastodon.cloud/@thomaslevesque">
```

(in `baseof.html`)

**Comment by shakasan** [comment]
@thomaslevesque added and good to know, thx ;-)
Sorry for linter issues by the way.

**Comment by Vimux** [comment]
I don't plan to add Mastodon to our list, certainly not now, sorry. The custom social links feature exists for that purpose. Embedded icons have increased requirements, for the most because of our license and the nature of SVG itself.

P.S. Icon looks broken. Perhaps aggressive SVGO settings or something else caused that.

**Comment by Jean85** [comment]
> The custom social links feature exists for that purpose.

Custom link is unfortunately not enough: to get the "verified" status for the link, you need a link with `rel="me"` as an attribute, and there's no easy way to do it as of now, without overriding the whole social widget partial.

**Comment by thomaslevesque** [comment]
> Custom link is unfortunately not enough: to get the "verified" status for the link, you need a link with `rel="me"` as an attribute, and there's no easy way to do it as of now, without overriding the whole social widget partial.

Hence #308 😉

**Pull request closed without merging**
