### PR TITLE
Added Italian translation

### PR DESCRIPTION
**Pull request by BeTmAsTeR**
Italian translations of the theme strings

### CODE REVIEW

**Comment by BeTmAsTeR** [comment]
Yes, the literal translations would be "Etichetta" but it's really uncommon in this context, and "Tag is used insted"

"Tag" is also [defined by "Treccani"](http://www.treccani.it/vocabolario/tag2/), the reference dictionary for the Italian language

**Comment by Vimux** [comment]
Sorry, my fault.

I mean, this is the plural in the original. What about Italian?

**Comment by BeTmAsTeR** [comment]
We use Tag (without the 's') also for the plural

_Il tag_ <- Singular
_I tag_ <- Plural

**Comment by Vimux** [comment]
@BeTmAsTeR, Thank you.

**Pull request merged**
