### PR TITLE
Add ability to define which sections are considered post sections

### PR DESCRIPTION
**Pull request by andytson**
I prefer "blog" to "post" for urls, and this helped me to migrate from Wordpress without messing with permalink urls.

Also this will allow someone to include multiple sections if wanted.

### CODE REVIEW

**Comment by Vimux** [comment]
1) You must specify a default parameter. (For cases if the parameter is not specified in config.toml)
2) Change empty state message "As posts are added in **content/post** folder...". (Don't forget about multiple sections)

It would be nice to add a comment for PostSections in the readme

If there are any difficulties, I'm ready to help.

**Comment by andytson** [comment]
ok, 2 and the readme update is done
1, already had the ["post"] as a default via `default (slice "post")`, specified in the templates (I'm unaware if you can define theme config defaults in a better place. It would be nice if it were/is possible in the theme.toml

**Comment by Vimux** [comment]
Good job. Really useful feature.

About point 2: Everything is OK. Excuse me, it's my fault. I missed it.

**Comment by andytson** [comment]
oh :( sadly printf isn't available in Hugo 0.19

**Pull request merged**
