### PR TITLE
Add thumbnail visibility options

### PR DESCRIPTION
**Pull request by BeTmAsTeR**
refs #160 

Add the ability to show/hide the thumbnail image inside post and/or the homepage, both options default to true

### CODE REVIEW

**Comment by jorgepiloto** [comment]
Thank you for opening this @BeTmAsTeR! I am interested in this particular feature. What do you think about the status of this, @Vimux? Is it ready to be merged? It looks like all tests passed 👍🏽

**Comment by Vimux** [comment]
Hi @jorgepiloto,

The current implementation is not ready enough:

Critical:

1. Params:
    1. Unclear naming:`show_thumb_in_home` not only for the home page but for all list-like pages
    1. Hard to remember both params (without README). Take a look at any other theme-defined front-matter parameters.
    1. Three underscores are overkill.
    1. It might be worth considering how to add this. I mean not only the name but also the structure itself (map?).
1. Complex thumbnail (adding new params increases complexity) requires separation into a separate part. Better to do separation first, in an isolated PR, but with this PR and possibly other changes (#57?) in mind, other than complete remade/find hacks for this repeatedly in the future.

Minor:

1. Tabs/spaces mixing
1. EOL changes

**Comment by jorgepiloto** [comment]
Thanks @Vimux for listing the different suggestions and requested changes. Hopefully @BeTmAsTeR or another user may apply them. I wish my knowledge of Hugo was deeper so I could help you with some of the work in this project. Really like this theme! ❤️

**Comment by Vimux** [comment]
@jorgepiloto,

Not sure if this is still relevant for you, but it should work now.

**Comment by jorgepiloto** [comment]
Thanks for implementing this @Vimux! 🎉

I took a view to the pull request and really like the way this can be configured, either globally or for a particular post. Working fine locally 👍🏽

**Pull request closed without merging**
