### PR TITLE
Use local fonts instead of Google Hosted Fonts

### PR DESCRIPTION
**Pull request by rmacd**
Theme depends on external resources and so is not optimal for use in situations where site
should be accessible locally / offline (eg internally / within company).

This pull request is therefore to update theme to use local Open Sans font.

### CODE REVIEW

**Comment by kofemann** [comment]
https://www.apache.org/licenses/GPL-compatibility.html

**Comment by Vimux** [comment]
https://www.apache.org/licenses/GPL-compatibility.html states:


>Despite our best efforts, the FSF has never considered the Apache License to be compatible with GPL version 2, citing the patent termination and indemnification provisions as restrictions not present in the older GPL license. The Apache Software Foundation believes that you should always try to obey the constraints expressed by the copyright holder when redistributing their work.

**Comment by rmacd** [comment]
Good shout, thanks!

Will update pull request to use Liberation Sans (is compatible); is v similar to Open Sans.

**Comment by Vimux** [comment]
I do not plan to change the main font. Liberation Sans is not comparable to Open Sans: it's two different fonts. And it's pretty-pretty noticeable.

Open Sans: https://mainroad.netlify.app/
Liberation Sans: https://deploy-preview-212--mainroad.netlify.app/

I understand your intention to use local fonts, but switching the main font is a breakable change too. Right now, I close this PR. If you have an idea of how to implement this in a non-breakable way, then open a new issue with all details first.

**Comment by Vimux** [comment]
@rmacd, Thanks.

**Comment by rmacd** [comment]
No problem / you're welcome. Will raise a separate issue once I revisit options.

**Comment by gleicher** [comment]
From a user perspective... Any change in font is "breaking" since it changes the appearance. 
However: it would be nice to have the font be "parameterized" - for example, to be able to put a font to over-ride the default into the configuration. This might be possible by making the css file a template, but that is beyond my hugo skills.
If someone were to find a way to create that feature, I would use it - there are some cases where I would love to override the typeface choices.

**Pull request closed without merging**
