### PR TITLE
fix(i18n): typo & style in zh-cn

### PR DESCRIPTION
**Pull request by yuqingc**
- Some charactors are in zh-tw. It is fixed to zh-cn

- Add a space between words to fix style issue

- Fix punctuation（Use fullwidth）

### CODE REVIEW

**Review by Vimux — COMMENTED** [review]
Hello,

One question: what's wrong with our `…` and `!` signs? I don't want to introduce different signs because of consistency across our i18n files.

**Comment by yuqingc** [comment]
@Vimux Hi. In the CN language, we use a different mark system from English. Since CN character takes more spaces(usually 2), we use fullwidth for all marks for consistency. For instance, you could see there is a `。` rather than `.` as a period in the original file:

https://github.com/Vimux/Mainroad/blob/8c2da72f92947e0bda55eacce1a70df8c3296ba5/i18n/zh-cn.yaml#L74

and

https://github.com/Vimux/Mainroad/blob/8c2da72f92947e0bda55eacce1a70df8c3296ba5/i18n/zh-cn.yaml#L92

Other transforms are:

- `,` for `，`, which is correctly used in

https://github.com/Vimux/Mainroad/blob/8c2da72f92947e0bda55eacce1a70df8c3296ba5/i18n/zh-cn.yaml#L85

- `“”` for `""`
- `！` for `!`

Although some pairs of those CN & EN marks look *the same*, they are totally distinct.

I find the original file uses `...` in

https://github.com/Vimux/Mainroad/blob/8c2da72f92947e0bda55eacce1a70df8c3296ba5/i18n/zh-cn.yaml#L42

but uses `"…"` in

https://github.com/Vimux/Mainroad/blob/8c2da72f92947e0bda55eacce1a70df8c3296ba5/i18n/zh-cn.yaml#L3

I made this change to make them consistent with each other.

By the way, I myself is using Mainroad for my [own website](https://yuqingc.github.io/). Mainroad is great, thanks for your work!

**Comment by Vimux** [comment]
@yuqingc,

Thank you for the detailed explanation. 

---

> I find the original file uses `...` in ... I made this change to make them consistent with each other.

Yeah. This inconsistency present in all our i18n files. I did this on purpose. As far as I remember, when I add `…` in the search placeholder, it looks a little weird for small font size (11px?) for some reason. It was noticeable. **So, could you please return `...` again, before I merge this PR**? I need to double-check `...` & `…` once more, but not now.

**Comment by shenfei** [comment]
Neither `...` nor `…` is a formal punctuation in Chinese. The correct ellipsis form is `……`. (Using `Shift + 6` to type in most of Chinese input methods).

Some references (sorry they are all in Chinese):

- [PRC national standard: GB/T 15834-2011](http://www.moe.gov.cn/ewebeditor/uploadfile/2015/01/13/20150113091548267.pdf)
- A [zhihu answer](https://www.zhihu.com/question/19602454/answer/12705421) by [Liang Hai](https://lianghai.github.io/), a font expert.
- [《别再用「六个点」当省略号了，这些标点都有更规范的输入方式》](https://sspai.com/post/45516) (Translation: *Do not use 6 dot as ellipsis, those punctuation have formal input methods*)

**Comment by Vimux** [comment]
@shenfei

TIL:

> Neither `...` nor `…` is a formal punctuation in Chinese. The correct ellipsis form is ……

Anyway, it looks like even Chinese sites do not strictly follow such typographical rules:

https://sspai.com/post/45516

Screen Shot 2020-11-06 at 07 37 20

https://zhuanlan.zhihu.com/p/129823316:
 
Screen Shot 2020-11-06 at 09 05 14

**Comment by yuqingc** [comment]
> @yuqingc,
> 
> Thank you for the detailed explanation.
> 
> > I find the original file uses `...` in ... I made this change to make them consistent with each other.
> 
> Yeah. This inconsistency present in all our i18n files. I did this on purpose. As far as I remember, when I add `…` in the search placeholder, it looks a little weird for small font size (11px?) for some reason. It was noticeable. **So, could you please return `…` (line 3) again, before I merge this PR**?
> 
> https://github.com/Vimux/Mainroad/blob/8c2da72f92947e0bda55eacce1a70df8c3296ba5/i18n/zh-cn.yaml#L3
> 
> I need to double-check `...` & `…` once more, but not now.

@Vimux Hi, I have recovered the mark in line 3.

**Review by Vimux — APPROVED** [review]
Looks good to me. Thank you.

**Pull request merged**
