### PR TITLE
comment out youtube icon

### PR DESCRIPTION
**Pull request by 10leej**
icon youtube.svg file does not exist

### CODE REVIEW

**Comment by Vimux** [comment]
No. If somebody for some reason can't read a very clear statement right behind the configuration example, it's not my problem.

> A good idea is not to copy all these settings without understanding how it works. Use only those parameters that you need.

**Comment by Vimux** [comment]
Duplicate #224

**Comment by 10leej** [comment]
> No. If somebody, for some reason, can't read a very clear statement right behind the configuration example, it's not my problem.

I mean I read it clearly saw it, but don't see why the example is even there if your not going to have the icon there for the example.

**Comment by Vimux** [comment]
It's a **custom** social link with a **custom** icon. "**Custom**" word means that you can add any link with (or without) a custom icon outside our theme.

So, this is just an example to show users what it might look like if they want to add a custom icon in the social widget list.

**Comment by 10leej** [comment]
So you're showing the config for custom links twice then?

**Comment by Vimux** [comment]
> So you're showing the config for custom links twice then?

So, what's your point?

**Comment by 10leej** [comment]
Just seem's like bad practice to me, that's all

**Pull request closed without merging**
