### PR TITLE
Option to Favicon

### PR DESCRIPTION
**Pull request by matheusrocha89**
This PR creates a new param on `config.toml` to add a favicon if the user wants.

### CODE REVIEW

**Comment by Vimux** [comment]
One change - two commits? I don't think it is a good practice.

**P.S.** IF we create an option, it should work out-of-the-box, right? Without favicon it will not work correctly. It is necessary to add a favicon in theme and description for the new option in REAMDE.md file ("Example config.toml" section). I want to hear your thoughts.

**Comment by matheusrocha89** [comment]
You can make a squash merge and this became just one commit 😄 .

By default if you not put the favicon It will use the hugo by default, I think it's a default fallback in Hugo. And you are correct, I need to put that on docs. I will do that on this PR. Thanks to remember me that @Vimux 👍

**Comment by matheusrocha89** [comment]
@Vimux I updated the readme, even with the fallback do you think we need to add a favicon to the theme? If you say so I can put one, if not I think we can merge this PR. 

**PS**: I will work on the social media widget today and try to open a PR for it.

**Comment by Vimux** [comment]
Thank you, @matheusrocha89 

I think we need to add a favicon to the theme anyway. But...

I want to make a custom favicon for Mainroad. Honestly, I already had a few attempts, but I don't really like the result. Maybe we should hold your pull request, until I make a good favicon? Main demo (themes.gohugo.io) cache is unpredictable, If we add blank icon now, we need a lot of time to refresh a new icon later.

**Comment by matheusrocha89** [comment]
@Vimux ok, no problem. Can you show me these icons? Maybe we can find a solution together.

**Comment by Vimux** [comment]
I added favicon support, but without params in config.toml.

**Pull request closed without merging**
